name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8 bandit locust

    - name: Run Flake8
      run: |
        # Stops the workflow if Flake8 raises any warnings
        flake8 ./app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Bandit
      run: |
        # Fail the step if any critical vulnerabilities are found
        bandit -r ./app -lll -iii