name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8 bandit aiogram-unittest locust

    - name: Run Flake8
      run: |
        flake8 ./app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Bandit
      run: |
        bandit -r ./app -lll -iii

    - name: Run pytest
      run: |
        pytest ./app/tests

    - name: Run pytest-cov
      run: |
        pytest --cov-fail-under=60 --cov=./app ./app/tests/
