name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Create .env file
      run: |
        echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} > .env

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8 bandit aiogram-unittest locust

    - name: Run Flake8
      run: |
        flake8 ./app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Bandit
      run: |
        bandit -r ./app -lll -iii

    - name: Run pytest
      run: |
        export PYTHONPATH=$PWD   
        pytest ./app/tests

    - name: Run pytest-cov
      run: |
        export PYTHONPATH=$PWD   
        pytest --cov-fail-under=60 --cov=./app ./app/tests/
